services:
 - docker
install:
  - docker build -t unifi .
  - docker run -d -p 8443:8443 -e RUNAS_UID0=true --name unifiroot unifi 
  - docker run -d -p 8444:8443 -e RUNAS_UID0=false --name unifi unifi 
script:
  - docker ps | grep -q unifi
  - docker logs unifi
  - sleep 10 && curl -k -L --fail https://127.0.0.1:8443 || exit 1
  - sleep 10 && curl -k -L --fail https://127.0.0.1:8444 || exit 1
